<?php

/**
 * Implements hook_page_alter().
 */
function modos_page_alter(&$page) {
  if ($alter = _modos_alter_get()) {
    if ($alter['hide_messages']) {
      global $user;
      if ($user->uid != 1) {
        $page['#show_messages'] = FALSE;
      }
    }
    if ($alter['page_title'] && $purl = vsite_get_purl()) {
      $vsite_domain_name = variable_get('vsite_domain_name', '');
      $request_path = request_path();
      if (!$vsite_domain_name) {
        $request_path = substr(request_path(), strlen($purl) + 1);
      }
      foreach ($alter['page_title'] as $pattern => $title) {
        if (drupal_match_path($request_path, $pattern)) {
          drupal_set_title($title);
        }
      }
    }
  }
}

/**
 * 
 */
function _modos_alter_get($purl = NULL) {
  if (!$purl) {
    $purl = vsite_get_purl();
  }
  if ($alter = _modos_alter_query($purl)) {
    return $alter;
  }
  return FALSE;
}

/**
 *
 */
function _modos_alter_query($purl) {
  $return = array();
  //dpm($purl);
  switch ($purl) {
    case 'petersnoad':
      $return['hide_messages'] = TRUE;
      $return['page_title'] = array(
        'publications' => t('Works'),
        'contact_owner' => t('Contact Me'),
      );
      break;
    case 'makeshiftboston':
      $return['hide_messages'] = TRUE;
      break;
  }
  return empty($return) ? FALSE : $return;
}

